server:
  port: 8083
  max-http-header-size: 100KB
  servlet:
    session:
      timeout: 1800s
spring:
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
#    static-path-pattern: /static/**,/webjars/**
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  application:
    name: pageServer
dapeng:
  cloud:
    teachingRequestUrl: ${TEACHING_REQUEST_URL:http://localhost:8080}

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8080/eureka/
